### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by mc9625** [debsahu/GoogleSay#2]
Hi, I'm trying to make your code work, but something doesn't work properly. Not for me at least. The only sound I can get from Google Home is a beep at boot, and the same beep when press the speak button. I've installed both required library and can't get any error message at all. Any suggestion? Do I miss some step?

**Comment by debsahu** [comment]
Could you try the [included example](https://github.com/horihiro/esp8266-google-home-notifier/blob/master/examples/esp8266/SimpleUsage/SimpleUsage.ino) with the esp8266-google-home-notifier library? Remember **displayName** must match the name of google home in the app.

**Comment by debsahu** [comment]
Update all libraries and reupload your code. Looks like Google has changed its endpoint of mp3 it generates. Updated library gets the correct ones.
